import hashlib
import json

###############################################################################
# RESOURCE COMMAND: REFERENCE IMPLEMENTATION (v2.5 - Dynamic Royalty Rate)
#
# DISCLAIMER & LIMITATION FOR AUDITORS (E.G., BARRY WHITEHAT / TRAIL OF BITS):
# This script defines the arithmetic consistency rules for the ZK-circuit.
# It serves as a reference for the ARITHMETIC LOGIC ONLY.
#
# CRITICAL NOTE ON COMMITMENT HESSING:
# Line 26 computes the volume commitment hash using SHA-256. The actual
# compliance.circom circuit implements a Poseidon(2) hash over the BN254 field.
# Consequently, witness commitments generated by this script will NOT match
# the Poseidon commitments expected by the circuit. This script should NOT
# be used to generate valid witnesses for circuit execution.
###############################################################################

BN254_PRIME = 21888242871839275222246405745257275088548364400416034343698204186575808495617

def mod_inverse(a, p):
    """Calculates the modular inverse of a in GF(p) using Fermat's Little Theorem."""
    if a == 0: return 0 # Soundness check: circuit will fail for 0
    return pow(a, p - 2, p)

def generate_witness(volume_v, density_d, grade_g, volume_nonce, royalty_rate_bps=600, scale=1000000):
    """
    Computes the R1CS witness signals including remainder witnesses 
    and modular inverses for the compliance.circom circuit.
    """
    
    # 1. Truth Anchor Commitment
    volume_commitment_hash = hashlib.sha256(f"{volume_v}{volume_nonce}".encode()).hexdigest()
    
    # 2. Tonnage Calculation (volume * density = tonnage * 10^6 + rem)
    vol_dens = volume_v * density_d
    tonnage_t = vol_dens // scale
    rem_tonnage = vol_dens % scale
    
    # 3. Mineral Content Calculation (tonnage * grade = mineral * 10^6 + rem)
    ton_grad = tonnage_t * grade_g
    mineral_content_m = ton_grad // scale
    rem_mineral = ton_grad % scale
    
    # 4. Royalty Attestation (mineral * royalty_rate_bps = tax_paid * 10000 + rem)
    lhs = mineral_content_m * royalty_rate_bps
    tax_paid_usd = lhs // 10000
    rem_royalty = lhs % 10000
    
    # 5. Optimized Witnesses (v2.5)
    inv_density_d = mod_inverse(density_d, BN254_PRIME)
    inv_grade_g = mod_inverse(grade_g, BN254_PRIME)
    
    return {
        "volume_commitment_hash": volume_commitment_hash,
        "tax_paid_usd": str(tax_paid_usd),
        "royalty_rate_bps": str(royalty_rate_bps),
        "volume_v": str(volume_v),
        "density_d": str(density_d),
        "grade_g": str(grade_g),
        "volume_nonce": str(volume_nonce),
        "inv_density_d": str(inv_density_d),
        "inv_grade_g": str(inv_grade_g),
        "rem_tonnage": str(rem_tonnage),
        "rem_mineral": str(rem_mineral),
        "rem_royalty": str(rem_royalty)
    }

if __name__ == "__main__":
    # Example: Mingomba Mine Parameters
    # Volume: 450,000 m3
    # Density: 2.7 t/m3
    # Grade: 4.5% Cu
    witness = generate_witness(450000000000, 2700000, 45000, 99128374)
    print(json.dumps(witness, indent=4))
